main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login_view, name="login"),
    path('skills/', views.skills_index, name='skills_index'),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('skills/add/', views.SkillAdd.as_view(), name='skills_add'),
    path('skills/<int:skill_id>/', views.skills_detail, name='skills_detail'),
]

mydevskills/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
LEVELS = (
    (1, 'Fundamental Awareness'),
    (2, 'Novice'),
    (3, 'Intermediate'),
    (4, 'Advanced'),
    (5, 'Expert'),
)


class Skill(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    level = models.IntegerField(
       # add the 'choices' field option
       choices=LEVELS,
       # set the default value for meal to be 'B'
       default=LEVELS[0][0]
       )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main_app/forms.py
from django.forms import ModelForm, Form, CharField, PasswordInput

class LoginForm(Form):
    username = CharField(label="User Name", max_length=64)
    password = CharField(widget=PasswordInput())

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from .models import Skill
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class SkillAdd(CreateView):
    model = Skill
    fields = '__all__'
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/skills/')

        
def index(request):
    return render(request, 'index.html')


def skills_index(request):
	skills = Skill.objects.all()
	return render(request, 'skills/index.html', { 'skills': skills })


def login_view(request):
    if request.method == 'POST':
        # if post, then authenticate (user submitted username and password)
        form = LoginForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    print("The account has been disabled.")
                    return HttpResponseRedirect('/')
            else:
                print("The username and/or password is incorrect.")
                return HttpResponseRedirect('/')
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

def skills_detail(request, skill_id):
    skill = Skill.objects.get(id=skill_id)
    return render(request, 'skills/detail.html', {'skill':skill})

main_app/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Dev Skills</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
        <nav>
            <div>
                <ul>
                    <li><a href="/">Dev Skills Home</a></li>
                    <li><a href="/skills">My Skills</a></li>
                    <li><a href="/skills/add">Add Skills</a></li>
                    {% if user.is_authenticated %}
                    
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    
                    <li><a href="{% url 'login' %}">Login</a></li>
                    
                    <li><a href="{% url 'signup' %}">SignUp</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>footer</footer>
</body>
</html>

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form method="POST" action=".">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/main_app/skill_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

main_app/templates/skills/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Skill Details</h1>

<div>
    <h3>{{ skill.name }}</h3>
    <p>{{ skill.description }}</p>
    <p>{{ skill.get_level_display }}</p>
</div>

{% endblock %}

main_app/templates/skills/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Skills</h1>
{% for skill in skills %}
    <h3>{{ skill.name }}</h3>
    <a href="{% url 'skills_detail' skill.id %}">{{ skill.description }}</a>
{% endfor %}

{% endblock %}